version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=atforestry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres      
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ../infrastructure/db/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  fetch-data:
    build: 
      context: ../fetch-data/
      dockerfile: ../fetch-data/Dockerfile
    image: "atforestry/fetch-data"
    ports:
      - "8000:8000" 
    volumes:
      - ../fetch-data/src:/app/src
    env_file:
      - ../fetch-data/.env_key
    depends_on:
      db:
        condition: service_healthy 
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5          
  batch-run:
    build: 
      context: ../batch-run
      dockerfile: ../batch-run/Dockerfile
    image: "atforestry/batch-run"
    ports:
      - "8010:8000" 
    volumes:
      - ../batch-run/src:/usr/src/app/src       
    depends_on:
      fetch-data:
        condition: service_healthy       
  model-predict:
    build: 
      context: ../model-predict
      dockerfile: ../model-predict/Dockerfile
    image: "atforestry/model-predict"
    ports:
      - "8020:8000" 
    volumes:
      - ../model-predict/src:/usr/src/app/src       
  api:
    build: 
      context: ../api
      dockerfile: ../api/Dockerfile
    image: "atforestry/api"
    ports:
      - "8030:80" 
    volumes:
      - ../api/src:/usr/src/app/src       
    depends_on:
      db:
        condition: service_healthy   
  user-query:
    build: 
      context: ../user-query/
      dockerfile: ../user-query/Dockerfile.local
    image: "atforestry/user-query"
    ports:
      - "8080:8080" 
    volumes:
      - ../user-query/app/src:/usr/src/app/src
    env_file:
      - ../user-query/.env
volumes:
  db:
    driver: local